name: execute
on:
  push:
    branches-ignore:
      - 'master'
      - 'production'
jobs:
  exec-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Installing theme dependencies
        working-directory: ./packages/theme/basic-test
        run: npm i
      - name: Run linting command
        working-directory: ./packages/theme/basic-test
        run: node ../../cli/cli.js lint
  exec-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Installing theme dependencies
        working-directory: ./packages/theme/basic-test
        run: npm i
      - name: Run build command
        working-directory: ./packages/theme/basic-test
        run: node ../../cli/cli.js build
  exec-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Installing theme dependencies
        working-directory: ./packages/theme/basic-test
        run: npm i
      - name: Run deploy command
        working-directory: ./packages/theme/basic-test
        run: node ../../cli/cli.js deploy
        env:
          THEME_ID: ${{ secrets.THEME_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          STORE: ${{ secrets.STORE }}
      - run: node ./test/scripts/validate-filtered-files.js