name: execute-sync
on:
  push:
    branches-ignore:
      - 'master'
      - 'production'
jobs:
  sync-to-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SYNC_SSH_KEY_GITHUB }}
          known_hosts: ${{ secrets.SYNC_KNOWN_HOSTS_GITHUB }}
      - run: git config --global init.defaultBranch master
      - run: git config --global user.email "ci@halfhelix.com"
      - run: git config --global user.name "Half Helix"
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Installing theme dependencies
        working-directory: ./packages/theme/basic-test
        run: npm i
      - name: Run sync to build repo command
        working-directory: ./packages/theme/basic-test
        run: node ../../cli/cli.js build --sync-with-repo
        env:
          BUILT_THEME_REPO_URL: ${{ secrets.BUILT_THEME_REPO_URL }}
      - run: node ./test/scripts/validate-filtered-files.js
  sync-to-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SYNC_SSH_KEY_GITHUB_TO_SOURCE }}
          known_hosts: ${{ secrets.SYNC_KNOWN_HOSTS_GITHUB }}
      - run: git config --global init.defaultBranch master
      - run: git config --global user.email "ci@halfhelix.com"
      - run: git config --global user.name "Half Helix"
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Installing theme dependencies
        working-directory: ./packages/theme/basic-built-theme-test
        run: npm i
      - name: Run sync to source repo command
        working-directory: ./packages/theme/basic-built-theme-test
        run: node ../../cli/cli.js sync-back-to-source-repo
        env:
          SRC_THEME_REPO_URL: ${{ secrets.SRC_THEME_REPO_URL }}
      - name: Validate files exit in source repo
        run: ./test/scripts/validate-source-sync.sh
        env:
          SRC_THEME_REPO_URL: ${{ secrets.SRC_THEME_REPO_URL }}